version: "3.7"

services:
    # image project
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - laravel

    # db mysql
    db:
        image: mysql:8.0
        volumes:
            - ./docker/mysql:/docker-entrypoint-initdb.d
            - ./docker/mysql/data:/var/lib/mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "33066:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: backend
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        networks:
            - laravel

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
